spring.application.name=biblioteca-horizonte
server.port=8080

# Perfil activo por defecto
spring.profiles.active=dev

# Formato JSON
spring.jackson.date-format=yyyy-MM-dd'T'HH:mm:ss'Z'
spring.jackson.time-zone=UTC
