-- Esquema relacional optimizado para PostgreSQL con índice condicional parcial (RN-001)
CREATE TABLE IF NOT EXISTS equipos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(120) NOT NULL
);

CREATE TABLE IF NOT EXISTS docentes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(120) NOT NULL
);

CREATE TABLE IF NOT EXISTS reservas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    docente_id BIGINT NOT NULL,
    equipo_id BIGINT NOT NULL,
    fecha DATE NOT NULL,
    modulo VARCHAR(50) NOT NULL,
    estado VARCHAR(20) NOT NULL,
    fecha_creacion TIMESTAMP NOT NULL,
    CONSTRAINT fk_reservas_equipo FOREIGN KEY (equipo_id) REFERENCES equipos(id),
    CONSTRAINT chk_reservas_estado CHECK (estado IN ('PENDIENTE', 'CONFIRMADA', 'RECHAZADA'))
);

-- Regla RN-001: Restricción física en base de datos PostgreSQL
CREATE UNIQUE INDEX IF NOT EXISTS uq_reserva_confirmada_slot 
ON reservas (equipo_id, fecha, modulo) 
WHERE estado = 'CONFIRMADA';
